# Generated by Django 4.1.3 on 2022-11-21 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('type', models.CharField(choices=[('1', 'کتاب گرد'), ('2', 'پخش مستند'), ('3', 'دوره های آموزشی'), ('4', 'همایش')], max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('capacity', models.IntegerField()),
                ('enrolled', models.IntegerField(blank=True, default=0, null=True)),
                ('held', models.BooleanField(blank=True, default=False, null=True)),
                ('date_time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'title', 'type', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=11)),
                ('university', models.CharField(max_length=100)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.event')),
            ],
        ),
    ]
