# Generated by Django 4.1.3 on 2022-11-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='student_id',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
