# Generated by Django 4.1.3 on 2022-11-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_registrant_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='student_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
