# Generated by Django 4.1.3 on 2022-11-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_events_registrant_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrant',
            unique_together={('event', 'student_id', 'last_name')},
        ),
    ]
